config/routes.rb
Versus::Application.routes.draw do
  resources :comparisons do 
    resources :opponents
  end
  

  devise_for :users
  resources :users

  authenticated :user do
    root :to => 'home#index'
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid_Commentable::Comment
  attr_accessible :text, :author
  field :text, :type => String
  field :author, :type => String
  embedded_in :versus
end

app/models/comparison.rb
class Comparison
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongo::Voteable
  voteable self, :up => +1, :down => -1
  field :title, :type => String
  field :description, :type => String
  embeds_many :comments
  embeds_many :opponents
end

app/models/opponent.rb
class Opponent
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :description, type: String
  embedded_in :comparison
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongo::Voter
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  # run 'rake db:mongoid:create_indexes' to create indexes
  index({ email: 1 }, { unique: true, background: true })
  field :name, :type => String
  validates_presence_of :name
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :created_at, :updated_at
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  # GET /versuss
  # GET /versuss.json
  def index
    @comparisons = Comparison.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comparison }
    end
  end

  # GET /versuss/1
  # GET /versuss/1.json
  def show
    @comparison = Comparison.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comparison }
    end
  end

  # GET /versuss/new
  # GET /versuss/new.json
  def new
    @comparison = Comparison.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comparison }
    end
  end

  # GET /versuss/1/edit
  def edit
    @comparison = Comparison.find(params[:id])
  end

  # POST /versuss
  # POST /versuss.json
  def create
    @comparison = Comparison.new(params[:comparison])

    respond_to do |format|
      if @comparison.save
        format.html { redirect_to @comparison, notice: 'comparison was successfully created.' }
        format.json { render json: @comparison, status: :created, location: @comparison }
      else
        format.html { render action: "new" }
        format.json { render json: @comparison.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /versuss/1
  # PUT /versuss/1.json
  def update
    @comparison = Comparison.find(params[:id])

    respond_to do |format|
      if @comparison.update_attributes(params[:comparison])
        format.html { redirect_to @comparison, notice: 'versus was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comparison.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versuss/1
  # DELETE /versuss/1.json
  def destroy
    @comparison = Comparison.find(params[:id])
    @comparison.destroy

    respond_to do |format|
      format.html { redirect_to comparison_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @comparisons = Comparison.all
  end
end

app/controllers/opponents_controller.rb
class OpponentsController < ApplicationController
  # GET /opponents
  # GET /opponents.json
  def index
    @opponents = Opponent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @opponents }
    end
  end

  # GET /opponents/1
  # GET /opponents/1.json
  def show
    @opponent = Opponent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @opponent }
    end
  end

  # GET /opponents/new
  # GET /opponents/new.json
  def new
    @opponent = Opponent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @opponent }
    end
  end

  # GET /opponents/1/edit
  def edit
    @opponent = Opponent.find(params[:id])
  end

  # POST /opponents
  # POST /opponents.json
  def create
    @opponent = Opponent.new(params[:opponent])

    respond_to do |format|
      if @opponent.save
        format.html { redirect_to @opponent, notice: 'Opponent was successfully created.' }
        format.json { render json: @opponent, status: :created, location: @opponent }
      else
        format.html { render action: "new" }
        format.json { render json: @opponent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /opponents/1
  # PUT /opponents/1.json
  def update
    @opponent = Opponent.find(params[:id])

    respond_to do |format|
      if @opponent.update_attributes(params[:opponent])
        format.html { redirect_to @opponent, notice: 'Opponent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @opponent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opponents/1
  # DELETE /opponents/1.json
  def destroy
    @opponent = Opponent.find(params[:id])
    @opponent.destroy

    respond_to do |format|
      format.html { redirect_to opponents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opponents_helper.rb
module OpponentsHelper
end

app/views/comments/_form.html.erb
<p>Leave a comment</p>
<%= form_for [model,comment] do |f| %>
  <% if model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if comment.parent %>
    <%= f.hidden_field :parent, :value => comment.parent %>
  <% end %>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
   <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Update Comment</h1>

<%= render :partial => 'form', :locals => {:model => @model,:comment => @comment} %>

app/views/comments/index.html.erb
<% @model.comments_list.each do |comment| %>
  <p>
  <% if comment.deleted %>
  <strong>DELETED</strong>
<% end %>
  <%= comment.text%>
  </p>
<% end %>

app/views/comments/new.html.erb
<%= render :partial => 'form', :locals => {:model => @model, :comment => @comment}%>

app/views/comments/show.html.erb
<p>
  <%=@comment.author%>
</p>
<p>
  <%=@comment.text%>
</p>

app/views/comparisons/_form.html.haml
= form_for @comparison do |f|
  - if @comparison.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comparison.errors.count, "error")} prohibited this comparison from being saved:"
      %ul
        - @comparison.errors.full_messages.each do |msg|
          %li= msg

  .input
    

  .actions
    = f.submit 'Save'

app/views/comparisons/edit.html.haml
%h1 Editing proposal

= render 'form'

= link_to 'Show', @proposal
\|
= link_to 'Back', proposals_path

app/views/comparisons/index.html.haml
%h1 Listing proposals

%table
  %tr
    %th
    %th
    %th

  - @comparisons.each do |comparison|
    %tr
      %td= link_to 'Show', comparison
      %td= link_to 'Edit', edit_comparison_path(proposal)
      %td= link_to 'Destroy', comparison, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comparison', new_comparison_path

app/views/comparisons/new.html.haml
%h1 New comparison

= render 'form'

= link_to 'Back', comparisons_path

app/views/comparisons/show.html.haml
%p#notice= notice

-@comparison.comments_list.each do |comment|
  %p
    =comment.author
  %p
    =comment.text


= link_to "vote", 

= link_to "Leave a comment", new_comment_path(:proposal_id => @comparison.id.to_s)

= link_to 'Edit', edit_proposal_path(@comparison)
\|
= link_to 'Back', proposals_path

app/views/home/index.html.haml
%h3 Home

- @comparisons.each do |comparison|
  %p
    comparison.title
  %p
    comparison.description
    

= link_to 'create new comparison', new_comparison_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.top-bar{:data =>{:options=>"is_hover:false"}}
  %ul.title-area
    %li.name
      %h1
        =link_to 'versus', root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    %ul.right
      - if user_signed_in?
        %li
          = link_to 'Logout', destroy_user_session_path, :method=>'delete'
      - else
        %li
          = link_to 'Login', new_user_session_path
      - if user_signed_in?
        %li
          = link_to 'Edit account', edit_user_registration_path
      - else
        %li
          = link_to 'Sign up', new_user_registration_path

app/views/layouts/application-old.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Versus"
      %meta{:content => content_for?(:description) ? yield(:description) : "Versus", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    #container.container
      %header
        = render 'layouts/navigation'
        = render 'layouts/messages'
      #main{:role => "main"}
        = yield
      %footer
    / ! end of #container

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/[if IE 9 ] <html class="ie9" lang="en">
/ [if (gt IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Untitled"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "custom.modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{:class => "#{controller_name} #{action_name}"}
    = render 'layouts/navigation'
    = render 'layouts/messages' 
    .row
      = yield
    = render 'layouts/footer'

app/views/opponents/_form.html.haml
= form_for @opponent do |f|
  - if @opponent.errors.any?
    #error_explanation
      %h2= "#{pluralize(@opponent.errors.count, "error")} prohibited this opponent from being saved:"
      %ul
        - @opponent.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/opponents/edit.html.haml
%h1 Editing opponent

= render 'form'

= link_to 'Show', @opponent
\|
= link_to 'Back', opponents_path

app/views/opponents/index.html.haml
%h1 Listing opponents

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @opponents.each do |opponent|
    %tr
      %td= opponent.name
      %td= opponent.description
      %td= link_to 'Show', opponent
      %td= link_to 'Edit', edit_opponent_path(opponent)
      %td= link_to 'Destroy', opponent, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Opponent', new_opponent_path

app/views/opponents/new.html.haml
%h1 New opponent

= render 'form'

= link_to 'Back', opponents_path

app/views/opponents/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @opponent.name
%p
  %b Description:
  = @opponent.description

= link_to 'Edit', edit_opponent_path(@opponent)
\|
= link_to 'Back', opponents_path

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}